### ISSUE TITLE
Image.Saveを用いた場合, 特定の条件下においてVrcMetaDataWriter.Writeでエラーが発生する

### ISSUE THREAD

**Issue by gatosyocora** [KoyashiroKohaku/VrcMetaToolSharp#1]
画像をBitmapで読み込み後にVrcMetaDataWriterを使用すると場合によって以下のようなエラーが発生する
`System.ArgumentOutOfRangeException: 'Specified argument was out of the range of valid values.`

一度Bitmapクラスを経由する以下のようなコードの場合, 2度目の実行時にVrcMetaDataWriter.Writeにてエラーが発生する
```csharp
var bitmap = new Bitmap(filePath);
byte[] buffer;
using (var stream = new MemoryStream())
{
    bitmap.Save(stream, ImageFormat.Png);
    bitmap.Dispose();
    buffer = stream.GetBuffer();
}
buffer = VrcMetaDataWriter.Write(buffer, metaData);
File.WriteAllBytes(filePath, buffer);
```

以下のようなコードでは複数回試行してもエラーが発生しない
```csharp
var buffer = File.ReadAllBytes(filePath);
buffer = VrcMetaDataWriter.Write(buffer, metaData);
File.WriteAllBytes(filePath, buffer);
```

**Comment by gatosyocora** [comment]
以下のコードでは同様にBitmapクラスを利用したがエラーが発生しなかった
```csharp
var bitmap = new Bitmap(filePath);
var converter = new ImageConverter();
var buffer = (byte[])converter.ConvertTo(bitmap, typeof(byte[]));
bitmap.Dispose();
buffer = VrcMetaDataWriter.Write(buffer, metaData);
File.WriteAllBytes(filePath, buffer);
```

**Comment by koyashiro** [comment]
`MemoryStream.GetBuffer`メソッドで取得できるバイト配列には、未使用の割り当て済みバイトも含まれているようです。
https://docs.microsoft.com/ja-jp/dotnet/api/system.io.memorystream.getbuffer

![image](https://user-images.githubusercontent.com/6698252/84335847-cd0dc380-abd0-11ea-8c82-84d0ba4b33b1.png)

上記のケースでは`stream.Length`は`3828946`ですが、`stream.GetBuffer()`の配列サイズは`4194304`となっています。余計なバイト列が入っているため、PNG画像のパースに失敗しているようです。

本ケースは`MemoryStream.GetBuffer`メソッドではなく`MemoryStream.ToArray`メソッドを使う、もしくは`File.ReadAllBytes`メソッドを使うことで解決できます。

**Comment by koyashiro** [comment]
依存ライブラリの問題なので以下に移動。

https://github.com/KoyashiroKohaku/PngChunkUtil/issues/1
